# Generated by Django 6.0.2 on 2026-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttitle', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=4.0)),
                ('productimage', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'productcard',
            },
        ),
    ]
