# Generated by Django 6.0.2 on 2026-02-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcard_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcard',
            table='product_card',
        ),
    ]
